version: "3.6"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: docker-compose/php/Dockerfile
    image: telegram
    container_name: telegram-app
    environment:
      XDEBUG_CONFIG: "remote_host=localhost:9003 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - telegram

  db:
    image: mysql:5.7
    container_name: telegram-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - telegram

  nginx:
    image: nginx:alpine
    container_name: telegram-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - telegram

  node:
    build:
      context: ./
      dockerfile: docker-compose/node/Dockerfile
    image: telegram-node
    container_name: telegram-node
    ports:
      - 2223:2223
    volumes:
      - ./node:/var/www/node
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
    networks:
      - telegram

networks:
  telegram:
    driver: bridge

volumes:
  dbdata:
    driver: local